// game constants
export const STAGE_WIDTH:number = 640;
export const STAGE_HEIGHT:number = 640;
export const FRAME_RATE:number = 30;
export const SPRITE_SIZE:number = 64;

export const ASSET_MANIFEST:Object[] = [
    {
        type:"json",
        src:"./Lib/SpritesSheets/Player.json",
        id:"Player",
        data:0
    },
    {
        type:"image",
        src:"./Lib/SpritesSheets/Player.png",
        id:"Player",
        data:0
    },
    {
        type:"json",
        src:"./Lib/SpritesSheets/Guard.json",
        id:"Guard",
        data:0
    },
    {
        type:"image",
        src:"./Lib/SpritesSheets/Guard.png",
        id:"Guard",
        data:0
    },
    {
        type:"json",
        src:"./Lib/SpritesSheets/Target.json",
        id:"Target",
        data:0
    },
    {
        type:"image",
        src:"./Lib/SpritesSheets/Target.png",
        id:"Target",
        data:0
    },
    {
        type:"json",
        src:"./Lib/SpritesSheets/Environment.json",
        id:"Environment",
        data:0
    },
    {
        type:"image",
        src:"./Lib/SpritesSheets/Environment.png",
        id:"Environment",
        data:0
    },
    {
        type:"json",
        src:"./Lib/SpritesSheets/Background.json",
        id:"Background",
        data:0
    },
    {
        type:"image",
        src:"./Lib/SpritesSheets/Background.png",
        id:"Background",
        data:0
    },
    {
        type:"json",
        src:"./Lib/SpritesSheets/Endings.json",
        id:"Endings",
        data:0
    },
    {
        type:"image",
        src:"./Lib/SpritesSheets/Endings.png",
        id:"Endings",
        data:0
    },
];